In [1]:
import darts_new

In [2]:
# 'discount' by 'd' for every 3 darts thrown in order to evalaute relative speen of paths
d = 0.95

# how accurate is our player?
a = {
'pdd': 0.45,
'pds' : 0.325,
'ptt' : 0.4,
'pbb' : 0.40,
'pbob' : 0.4
}

In [3]:
p = darts_new.Player(d, a)

In [10]:
p.strategies

         first     second      third
0     finished   finished   finished
1         bust       bust       bust
2     double 1   double 1   double 1
3     single 1   single 1   single 1
4     single 1   single 2   single 2
5     single 1   single 3   single 3
6     single 1   single 4   single 4
7     single 1   single 5   single 5
8     single 1   single 6   single 6
9     single 1   single 7   single 7
10    single 1   single 8   single 8
11    single 1   single 9   single 9
12    single 1  single 10  single 10
13    single 1  single 11  single 11
14    single 1  single 12  single 12
15    single 1  single 13  single 13
16    single 1  single 14  single 14
17    single 1  single 15  single 15
18    single 1  single 16  single 16
19    single 1  single 17  single 17
20    single 1  single 18  single 18
21    single 1  single 19  single 19
22    single 1  single 20  single 20
23    single 1   triple 7   triple 7
24    single 2   single 2   single 1
25    single 3   single 3   single 1
26    single 4   triple 8   triple 8
27    single 5   single 5   single 1
28    single 6   single 6   single 1
29    single 7   triple 9   triple 9
..         ...        ...        ...
472  triple 20  triple 20  triple 20
473  triple 20  triple 20  triple 20
474  triple 20  triple 20  triple 20
475  triple 20  triple 20  triple 20
476  triple 20  triple 20  triple 20
477  triple 20  triple 20  triple 20
478  triple 20  triple 20  triple 20
479  triple 20  triple 20  triple 20
480  triple 20  triple 20  triple 20
481  triple 20  triple 20  triple 20
482  triple 20  triple 20  triple 20
483  triple 20  triple 20  triple 20
484  triple 20  triple 20  triple 20
485  triple 20  triple 20  triple 20
486  triple 20  triple 20  triple 20
487  triple 20  triple 20  triple 20
488  triple 20  triple 20  triple 20
489  triple 20  triple 20  triple 20
490  triple 20  triple 20  triple 20
491  triple 20  triple 20  triple 20
492  triple 20  triple 20  triple 20
493  triple 20  triple 20  triple 20
494  triple 20  triple 20  triple 20
495  triple 20  triple 20  triple 20
496  triple 20  triple 20  triple 20
497  triple 20  triple 20  triple 20
498  triple 20  triple 20  triple 20
499  triple 20  triple 20  triple 20
500  triple 20  triple 20  triple 20
501  triple 20  triple 20  triple 20

[502 rows x 3 columns]